org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true
figura_version=0.1.6
luaj_version = 3.0.8
nv_websocket_version = 2.14
voicechat_api_version = 2.6.0

# maybe actually start following semver lmao
# so that was a fucking lie
# lets get that back on track....
silly_version = 1.2.1-alpha
